import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const questPath = path.join(process.cwd(), "src/app/quest/page.tsx");
const source = fs.readFileSync(questPath, "utf8");

test("quest skill mode uses learning session lifecycle", () => {
  assert.equal(source.includes('const skillIdFromQuery = (params.get("skillId") ?? "").trim();'), true);
  assert.equal(source.includes('const retryFromQuery = (params.get("retry") ?? "").trim();'), true);
  assert.equal(source.includes('const freshFromQuery = (params.get("fresh") ?? "").trim();'), true);
  assert.equal(source.includes('const isLearningSessionMode = Boolean(skillIdFromQuery);'), true);
  assert.equal(source.includes('fetch("/api/learning/session/start"'), true);
  assert.equal(source.includes('fetch(`/api/learning/session/${encodeURIComponent(sessionId)}`'), true);
  assert.equal(source.includes('fetch("/api/learning/session/answer"'), true);
  assert.equal(source.includes('fetch("/api/learning/session/finish"'), true);
  assert.equal(source.includes('import { trackAnalyticsEvent } from "@/lib/analytics";'), true);
  assert.equal(source.includes("const shouldAutoFinishLearningSession ="), true);
  assert.equal(source.includes("const finishGuardRef = useRef(false);"), true);
  assert.equal(source.includes("const advanceGuardRef = useRef(false);"), true);
  assert.equal(source.includes("const normalizedLearningSession = useMemo(() => {"), true);
  assert.equal(source.includes("const normalizedIndex = Math.min(learningSession.index, learningSession.problems.length);"), true);
  assert.equal(source.includes("if (normalizedLearningSession.index !== learningSession.index) {"), true);
  assert.equal(source.includes("setLearningSession({"), true);
  assert.equal(source.includes("const currentLearningIndex = normalizedLearningSession?.index ?? 0;"), true);
  assert.equal(source.includes("const [learningCurrentProblem, setLearningCurrentProblem] = useState<SessionProblem | null>(null);"), true);
  assert.equal(source.includes("const [learningAttemptCount, setLearningAttemptCount] = useState(0);"), true);
  assert.equal(source.includes("const [learningHint, setLearningHint] = useState<string | null>(null);"), true);
  assert.equal(source.includes("const [learningExplanation, setLearningExplanation] = useState<string | null>(null);"), true);
  assert.equal(source.includes("const syncLearningUiFromAnswer = useCallback((response: LearningSessionAnswerResponse) => {"), true);
  assert.equal(source.includes("setLearningCurrentProblem(response.problem ?? null);"), true);
  assert.equal(source.includes("setLearningAttemptCount(response.attemptCount ?? 0);"), true);
  assert.equal(source.includes("setLearningHint(response.hint ?? null);"), true);
  assert.equal(source.includes("setLearningExplanation(response.explanation ?? null);"), true);
  assert.equal(source.includes('console.log("finished:", data.finished);'), true);
  assert.equal(source.includes('console.log("SESSION FINISHED");'), true);
  assert.equal(source.includes("if (data.finished) {"), false);
  assert.equal(source.includes("const answeredSkillId = data.session.skillId ?? learningSession.skillId ?? skillIdFromQuery;"), true);
  assert.equal(source.includes("const reachedSkillXpTarget = Boolean(answeredSkillId) && answeredSkillXp >= requiredXpForAnsweredSkill;"), true);
  assert.equal(source.includes("if (data.finished || reachedSkillXpTarget) {"), true);
  assert.equal(source.includes("const result = await runFinishLearningSession();"), true);
  assert.equal(source.includes('console.log("FINISH RESULT:", result);'), true);
  assert.equal(source.includes('console.log("LEARNING RESULT SET");'), true);
  assert.equal(source.includes("currentLearningIndex >= (normalizedLearningSession?.session.problems.length ?? 0)"), true);
  assert.equal(source.includes("currentSkillXP >= currentSkillRequiredXP"), true);
  assert.equal(source.includes("const clearPendingAdvanceTimers = useCallback(() => {"), true);
  assert.equal(source.includes("const runFinishLearningSession = useCallback(async () => {"), true);
  assert.equal(source.includes("clearPendingAdvanceTimers();"), true);
  assert.equal(source.includes("return await finishQuestLearningSession();"), true);
  assert.equal(source.includes("await runFinishLearningSession();"), true);
  assert.equal(source.includes('console.error("finish failed", error);'), true);
  assert.equal(source.includes("if (finishGuardRef.current) {"), true);
  assert.equal(source.includes("finishGuardRef.current = true;"), true);
  assert.equal(source.includes("finishGuardRef.current = false;"), true);
  assert.equal(source.includes("const useFastLearningLoop = isLearningSessionMode;"), true);
  assert.equal(source.includes("const FEEDBACK_FLASH_MS = 150;"), true);
  assert.equal(source.includes("const AUTO_ADVANCE_MS = 300;"), true);
  assert.equal(source.includes("const queueAdvanceAfterFeedback = (verdict: { ok: boolean }) => {"), true);
  assert.equal(source.includes("if (advanceGuardRef.current) {"), true);
  assert.equal(source.includes("advanceGuardRef.current = true;"), true);
  assert.equal(source.includes("advanceGuardRef.current = false;"), true);
  assert.equal(source.includes("setResultMark(verdict.ok ? \"correct\" : \"wrong\");"), true);
  assert.equal(source.includes("}, FEEDBACK_FLASH_MS);"), true);
  assert.equal(source.includes("}, AUTO_ADVANCE_MS);"), true);
  assert.equal(source.includes("queueAdvanceAfterFeedback(verdict);"), true);
  assert.equal(source.includes("currentLearningAttemptCount >= 1"), true);
  assert.equal(source.includes("currentLearningAttemptCount >= 2"), true);
  assert.equal(source.includes("!useFastLearningLoop && ("), true);
  assert.equal(source.includes("{resultMark === \"correct\" ? \"Correct\" : \"Incorrect\"}"), true);
  assert.equal(source.includes("!shouldAutoFinishLearningSession && (quizItems.length === 0 || !currentItem)"), true);
  assert.equal(source.includes("void runFinishLearningSession().catch((error: unknown) => {"), true);
  assert.equal(source.includes("void finishQuestLearningSession().catch((error: unknown) => {"), false);
  assert.equal(source.includes("index: answerIndex"), true);
  assert.equal(source.includes("answer: answerText"), true);
  assert.equal(source.includes("carryoverHistory: options?.carryoverHistory"), true);
  assert.equal(source.includes("recentProblems: options?.recentProblems"), true);
  assert.equal(source.includes("const forceFreshStart = Boolean(freshFromQuery || retryFromQuery);"), true);
  assert.equal(source.includes('console.log("QUEST START");'), true);
  assert.equal(source.includes('console.log("fresh:", forceFreshStart);'), true);
  assert.equal(source.includes('console.log("hasRecovery:", hasRecovery);'), true);
  assert.equal(source.includes('console.log("learningResult:", learningResult);'), true);
  assert.equal(source.includes('console.log("session:", forceFreshStart ? null : (persistedSession ?? null));'), true);
  assert.equal(source.includes("const handleRetry = useCallback(() => {"), true);
  assert.equal(source.includes('console.log("RETRY CLICKED");'), true);
  assert.equal(source.includes("setLearningResult(null);"), true);
  assert.equal(source.includes('const nextUrl = `/quest?skillId=${encodeURIComponent(currentLearningSkillId)}&fresh=1`;'), true);
  assert.equal(source.includes("buildFreshLearningState(skillId)"), true);
  assert.equal(source.includes("clearPersistedLearningSession(skillIdFromQuery);"), true);
  assert.equal(source.includes("clearPersistedLearningSession(currentLearningSkillId);"), true);
  assert.equal(source.includes("LEARNING_STATE_KEY"), true);
  assert.equal(source.includes('const LS_LEARNING_SESSION = "mq:learningSession";'), true);
  assert.equal(source.includes('window.localStorage.removeItem("learningState");'), true);
  assert.equal(source.includes('window.localStorage.removeItem("studentStore");'), true);
  assert.equal(source.includes("window.localStorage.removeItem(LEARNING_STATE_KEY);"), false);
  assert.equal(source.includes("window.sessionStorage.clear();"), false);
  assert.equal(source.includes('console.log("preserve learning progress key:", LEARNING_STATE_KEY);'), true);
  assert.equal(source.includes("const ORDER_LEGACY_PROMPT_RE = /小さいほうから|小さい順|ならべよう/u;"), true);
  assert.equal(source.includes("const ORDER_NUMERIC_ANSWER_RE = /^-?\\d+$/u;"), true);
  assert.equal(source.includes("const shouldForceFreshOrderSession = ("), true);
  assert.equal(source.includes('skillId === "E1_NUMBER_ORDER"'), true);
  assert.equal(source.includes("ORDER_LEGACY_PROMPT_RE.test(problem.problem.question)"), true);
  assert.equal(source.includes("!ORDER_NUMERIC_ANSWER_RE.test(problem.problem.answer)"), true);
  assert.equal(source.includes("if (storedSession.skillId !== skillId) {"), true);
  assert.equal(source.includes("if (shouldForceFreshOrderSession(skillId, storedSession)) {"), true);
  assert.equal(source.includes('console.info("[quest] stale order session detected; starting fresh session"'), true);
  assert.equal(source.includes('console.info("[quest] order skill forces fresh session"'), true);
  assert.equal(source.includes("const clearLearningRecoveryStorage = () => {"), true);
  assert.equal(source.includes("const clearLearningRecovery = clearLearningRecoveryStorage;"), true);
  assert.equal(source.includes("const purgeFreshLearningRecovery = useCallback(() => {"), true);
  assert.equal(source.includes("resetLearningSessionUi();"), true);
  assert.equal(source.includes("setLearningSession(null);\n    setLearningState(null);"), false);
  assert.equal(source.includes("router.replace(nextUrl);"), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_start");'), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_finish");'), true);
  assert.equal(source.includes("sessionStartTrackedRef.current = true;"), true);
  assert.equal(source.includes('if (isLearningSessionMode) {'), true);
  assert.equal(source.includes('return postJson("/api/session/answer", {'), true);
  assert.equal(source.includes("<SkillClearView"), true);
  assert.equal(source.includes("history={learningResult.history}"), true);
  assert.equal(source.includes("onRetry={handleRetry}"), true);
  assert.equal(source.includes(") : learningResult ? ("), true);
  assert.equal(source.includes('console.log("learningResult state:", learningResult);'), true);
  assert.equal(source.includes('console.log("RENDER CLEAR");'), true);
  assert.equal(source.includes(") : false ? ("), false);
  assert.equal(source.includes(") : status === 'blocked' ? ("), true);
  assert.equal(source.includes('!isLearningSessionMode && selectedPath && ('), true);
});
