import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const questPath = path.join(process.cwd(), "src/app/quest/page.tsx");
const source = fs.readFileSync(questPath, "utf8");

test("quest uses random pool questions and next-level navigation", () => {
  assert.equal(source.includes("const TOTAL_QUESTIONS = 5;"), true);
  assert.equal(source.includes("const QUESTION_POOL_SIZE = 50;"), true);
  assert.equal(source.includes("buildUniqueQuestSet({"), true);
  assert.equal(source.includes("const sameTypeAcrossGrades = allCategoryItems.filter("), true);
  assert.equal(source.includes("setStatus('cleared');"), true);
  assert.equal(source.includes("クリアー！"), true);
  assert.equal(source.includes("if (v + 1 >= totalQuizQuestions)"), true);
  assert.equal(source.includes("const totalQuizQuestions = TOTAL_QUESTIONS;"), true);
  assert.equal(source.includes("const totalQuizQuestions = Math.min(TOTAL_QUESTIONS, quizItems.length);"), false);
  assert.equal(source.includes("setQuestionResults((prev) => ({"), true);
  assert.equal(source.includes("correctAnswer?: string"), true);
  assert.equal(source.includes("everWrong: boolean"), true);
  assert.equal(source.includes("firstWrongAnswer?: string"), true);
  assert.equal(source.includes("const finalWrong = r.everWrong === true;"), true);
  assert.equal(source.includes("r.firstWrongAnswer ?? r.userAnswer"), true);
  assert.equal(source.includes("correct: !everWrong"), true);
  assert.equal(source.includes("if (isDrawingRef.current) return \"\";"), true);
  assert.equal(source.includes("splitComponentGreedyByProjection"), true);
  assert.equal(source.includes("splitByProjection(bin, w, h, pivot.bbox, true"), true);
  assert.equal(source.includes("学習終了"), true);
  assert.equal(source.includes("次のレベルに進む"), true);
  assert.equal(source.includes("同じ問題を練習する"), true);
  assert.equal(source.includes("学習終了（レポート配信）"), true);
  assert.equal(source.includes("onClick={goToNextLevel}"), true);
  assert.equal(source.includes("onClick={restartSameLevel}"), true);
  assert.equal(source.includes("onClick={endLearningSession}"), true);
  assert.equal(source.includes("router.push(\"/\");"), true);
  assert.equal(source.includes("status === 'playing' && (inputMode === 'numpad' ? ("), false);
  assert.equal(source.includes("data-testid=\"calc-memo-area\""), true);
  assert.equal(source.includes("計算メモ（2本指ピンチで縮小）"), true);
  assert.equal(source.includes("h-[40vh] min-h-[260px]"), true);
  assert.equal(source.includes("bg-white/90"), true);
  assert.equal(source.includes("w-full bg-white border border-slate-200 rounded-xl p-4 shadow-sm max-h-[48vh] overflow-y-auto"), false);
  assert.equal(source.includes("h-[120%] w-[120%]"), true);
  assert.equal(source.includes("overflow-visible"), true);
  assert.equal(source.includes("fixed inset-x-2 bottom-2"), false);
  assert.equal(source.includes("status === 'playing' && selectedPath"), true);
  assert.equal(source.includes("まちがえた もんだい"), false);
  assert.equal(source.includes("`/quest?type=${encodeURIComponent(next.typeId)}&category=${encodeURIComponent(next.categoryId)}`"), true);
});
