import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const pageSource = fs.readFileSync(path.join(process.cwd(), "src/app/quest/page.tsx"), "utf8");
const libSource = fs.readFileSync(path.join(process.cwd(), "src/lib/elementaryExplanations.ts"), "utf8");
const panelSource = fs.readFileSync(path.join(process.cwd(), "src/components/ElementaryExplanationPanel.tsx"), "utf8");

test("quest shows elementary explanation in memo area when elementary answer is wrong", () => {
  assert.match(pageSource, /import ElementaryExplanationPanel from "@\/components\/ElementaryExplanationPanel"/);
  assert.match(pageSource, /getElementaryLearningAid/);
  assert.match(pageSource, /isElementaryGrade\(currentGradeId\)/);
  assert.match(pageSource, /practiceResult\?\.ok === false/);
  assert.match(pageSource, /<ElementaryExplanationPanel/);
  assert.match(pageSource, /onNext=\{nextQuestion\}/);
  assert.match(pageSource, /nextLabel=\{uiText\.nextQuestion\}/);
});

test("elementary explanation resolver has abacus/column_story/simple branches", () => {
  assert.match(libSource, /ElementaryAidKind = "abacus" \| "column" \| "column_story" \| "simple"/);
  assert.match(libSource, /mode: "abacus" \| "column" \| "column_story" \| "simple"/);
  assert.match(libSource, /kind: ElementaryAidKind;/);
  assert.match(libSource, /conclusion: string;/);
  assert.match(libSource, /numberingStyle\?: "decimal" \| "circled"/);
  assert.match(libSource, /embedAnswerInSteps\?: boolean/);
  assert.match(libSource, /cleanAnswerText\?: string/);
  assert.match(libSource, /const normalizeAnswerText =/);
  assert.match(libSource, /replace\(\/\[=＝\]\/g, " "\)/);
  assert.match(libSource, /const shouldUseCircledNumbering =/);
  assert.match(libSource, /const applyCircledStyle =/);
  assert.match(libSource, /③ こたえ：\$\{answerText\}/);
  assert.match(libSource, /const isColumnPattern =/);
  assert.match(libSource, /if \(!isColumnPattern\(typeId, patternId\)\)/);
  assert.match(libSource, /return finalize\(buildSimpleAid\(\)\);/);
  assert.match(libSource, /if \(patternId === "NUM_COMPARE_UP_TO_20"\)/);
  assert.match(libSource, /buildCompareUpTo20Aid/);
  assert.match(libSource, /if \(patternId === "NUM_DECOMP_10"\)/);
  assert.match(libSource, /buildTenDecompAid/);
  assert.match(libSource, /if \(patternId === "NUM_COMP_10"\)/);
  assert.match(libSource, /buildNumComp10Aid/);
  assert.match(libSource, /const buildColumnStoryFrames =/);
  assert.match(libSource, /kind: "column_story"/);
  assert.match(libSource, /mode: "column_story"/);
  assert.match(libSource, /frames: frames\.slice\(0, 5\)/);
  assert.match(libSource, /const collectDigitAdjustments =/);
  assert.match(libSource, /digitAdjustments/);
  assert.match(libSource, /marks\.push\(\{ offsetFromRight: place \+ 1, label: "\+1" \}\);/);
  assert.match(libSource, /marks\.push\(\{ offsetFromRight: place \+ 1, label: "-1" \}\);/);
  assert.match(libSource, /marks\.push\(\{ offsetFromRight: place, label: "\+10" \}\);/);
  assert.match(libSource, /const onesTop = operator === "-" && topOnes < bottomOnes \? topOnes \+ 10 : topOnes;/);
  assert.match(libSource, /: onesTop - bottomOnes;/);
  assert.match(libSource, /focusPlace: "ones"/);
  assert.match(libSource, /focusPlace: "next"/);
  assert.match(libSource, /title: "答え"/);
  assert.match(libSource, /partial: `答え: \$\{formatNumber\(result\)\}`/);
  assert.match(libSource, /if \(isSingleDigitPair\)/);
  assert.match(libSource, /return finalize\(buildAbacusAid/);
  assert.match(libSource, /return finalize\(buildColumnAid/);
  assert.match(libSource, /const finalize = \(aid: ElementaryLearningAid\)/);
  assert.match(libSource, /aDigits \?\? fallbackDigitCount\(left\)/);
  assert.match(libSource, /bDigits \?\? fallbackDigitCount\(right\)/);
});

test("elementary panel has next button and visual rendering", () => {
  assert.match(panelSource, /type Props = \{/);
  assert.match(panelSource, /onNext: \(\) => void;/);
  assert.match(panelSource, /nextLabel: string;/);
  assert.match(panelSource, /aid\.visual\?\.mode === "abacus"/);
  assert.match(panelSource, /aid\.visual\.showTenBundle/);
  assert.match(panelSource, /10のまとまり/);
  assert.match(panelSource, /aid\.visual\?\.mode === "column"/);
  assert.match(panelSource, /aid\.visual\?\.mode === "column_story"/);
  assert.match(panelSource, /aid\.steps\.length > 0/);
  assert.match(panelSource, /const isCircled = aid\.numberingStyle === "circled"/);
  assert.match(panelSource, /stepLabels = \["①", "②", "③"/);
  assert.match(panelSource, /step\.replace\(\/\^\[①②③④⑤⑥\]\\s\*\/u, ""\)/);
  assert.match(panelSource, /!aid\.embedAnswerInSteps/);
  assert.match(panelSource, /こたえ: \{aid\.cleanAnswerText \?\? aid\.conclusion\}/);
  assert.match(panelSource, /renderColumnFrame/);
  assert.match(panelSource, /renderAlignedValue/);
  assert.match(panelSource, /text-rose-600/);
  assert.match(panelSource, /text-indigo-600/);
  assert.match(panelSource, /digitAdjustments/);
  assert.match(panelSource, /adj\.offsetFromRight/);
  assert.match(panelSource, /adj\.label/);
  assert.match(panelSource, /const getAdjustmentBadgeClass =/);
  assert.match(panelSource, /if \(label === "-1"\) return "border-rose-300 bg-rose-500";/);
  assert.match(panelSource, /if \(label === "\+10"\) return "border-sky-300 bg-sky-500";/);
  assert.match(panelSource, /return "border-emerald-300 bg-emerald-500";/);
  assert.match(panelSource, /const stackIndexByOffset = new Map<number, number>\(\);/);
  assert.match(panelSource, /const stackIndex = stackIndexByOffset\.get\(adj\.offsetFromRight\) \?\? 0;/);
  assert.match(panelSource, /stackIndexByOffset\.set\(adj\.offsetFromRight, stackIndex \+ 1\);/);
  assert.match(panelSource, /const top = `calc\(-0\.75rem - \$\{stackIndex \* 1\.05\}rem\)`;/);
  assert.match(panelSource, /max-w-\[19rem\]/);
  assert.match(panelSource, /こたえ \{aid\.visual\.result\} こ/);
  assert.match(panelSource, /onClick=\{onNext\}/);
  assert.match(panelSource, /\{nextLabel\}/);
});

test("secondary explanation path remains in quest page", () => {
  assert.match(pageSource, /SecondaryExplanationPanel/);
  assert.match(pageSource, /getSecondaryLearningAid/);
  assert.match(pageSource, /isSecondaryQuest/);
  assert.match(pageSource, /showSecondaryHint/);
  assert.match(pageSource, /showSecondaryExplanation/);
  assert.match(pageSource, /ヒントを見る/);
  assert.match(pageSource, /解説を見る/);
  assert.match(pageSource, /showNextButton/);
  assert.match(pageSource, /skipFromExplanation/);
  assert.match(pageSource, /const \[showHighSchoolHint, setShowHighSchoolHint\] = useState\(false\);/);
  assert.match(pageSource, /isHighSchoolQuest \?/);
  assert.match(pageSource, /ヒントを閉じる/);
  assert.match(pageSource, /\{showHighSchoolHint && \(/);
  assert.match(pageSource, /<SecondaryExplanationPanel aid=\{currentAid\} \/>/);
});
