import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const questPath = path.join(process.cwd(), "src/app/quest/page.tsx");
const source = fs.readFileSync(questPath, "utf8");

test("quest skill mode uses learning session lifecycle", () => {
  assert.equal(source.includes('const skillIdFromQuery = (params.get("skillId") ?? "").trim();'), true);
  assert.equal(source.includes('const isLearningSessionMode = Boolean(skillIdFromQuery);'), true);
  assert.equal(source.includes('fetch("/api/learning/session/start"'), true);
  assert.equal(source.includes('fetch(`/api/learning/session/${encodeURIComponent(sessionId)}`'), true);
  assert.equal(source.includes('fetch("/api/learning/session/answer"'), true);
  assert.equal(source.includes('fetch("/api/learning/session/finish"'), true);
  assert.equal(source.includes('import { trackAnalyticsEvent } from "@/lib/analytics";'), true);
  assert.equal(source.includes("const shouldAutoFinishLearningSession ="), true);
  assert.equal(source.includes("const finishGuardRef = useRef(false);"), true);
  assert.equal(source.includes("const advanceGuardRef = useRef(false);"), true);
  assert.equal(source.includes("const normalizedLearningSession = useMemo(() => {"), true);
  assert.equal(source.includes("const normalizedIndex = Math.min(learningSession.index, learningSession.problems.length);"), true);
  assert.equal(source.includes("if (normalizedLearningSession.index !== learningSession.index) {"), true);
  assert.equal(source.includes("setLearningSession({"), true);
  assert.equal(source.includes("const currentLearningIndex = normalizedLearningSession?.index ?? 0;"), true);
  assert.equal(source.includes("currentLearningIndex >= (normalizedLearningSession?.session.problems.length ?? 0)"), true);
  assert.equal(source.includes("currentSkillXP >= currentSkillRequiredXP"), true);
  assert.equal(source.includes("await finishQuestLearningSession();"), true);
  assert.equal(source.includes('console.error("finish failed", error);'), true);
  assert.equal(source.includes("if (finishGuardRef.current) {"), true);
  assert.equal(source.includes("finishGuardRef.current = true;"), true);
  assert.equal(source.includes("finishGuardRef.current = false;"), true);
  assert.equal(source.includes("const useFastLearningLoop = isLearningSessionMode;"), true);
  assert.equal(source.includes("const FEEDBACK_FLASH_MS = 150;"), true);
  assert.equal(source.includes("const AUTO_ADVANCE_MS = 300;"), true);
  assert.equal(source.includes("const queueAdvanceAfterFeedback = (verdict: { ok: boolean }) => {"), true);
  assert.equal(source.includes("if (advanceGuardRef.current) {"), true);
  assert.equal(source.includes("advanceGuardRef.current = true;"), true);
  assert.equal(source.includes("advanceGuardRef.current = false;"), true);
  assert.equal(source.includes("setResultMark(verdict.ok ? \"correct\" : \"wrong\");"), true);
  assert.equal(source.includes("}, FEEDBACK_FLASH_MS);"), true);
  assert.equal(source.includes("}, AUTO_ADVANCE_MS);"), true);
  assert.equal(source.includes("queueAdvanceAfterFeedback(verdict);"), true);
  assert.equal(source.includes("currentLearningAttemptCount >= 1"), true);
  assert.equal(source.includes("currentLearningAttemptCount >= 2"), true);
  assert.equal(source.includes("!useFastLearningLoop && ("), true);
  assert.equal(source.includes("{resultMark === \"correct\" ? \"Correct\" : \"Incorrect\"}"), true);
  assert.equal(source.includes("!shouldAutoFinishLearningSession && (quizItems.length === 0 || !currentItem)"), true);
  assert.equal(source.includes("index: answerIndex"), true);
  assert.equal(source.includes("answer: answerText"), true);
  assert.equal(source.includes("carryoverHistory: options?.carryoverHistory"), true);
  assert.equal(source.includes("recentProblems: options?.recentProblems"), true);
  assert.equal(source.includes("loadStateFromClient()"), true);
  assert.equal(source.includes("LEARNING_STATE_KEY"), true);
  assert.equal(source.includes('const LS_LEARNING_SESSION = "mq:learningSession";'), true);
  assert.equal(source.includes("if (storedSession.skillId !== skillId) {"), true);
  assert.equal(source.includes("clearLearningRecovery();"), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_start");'), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_finish");'), true);
  assert.equal(source.includes("sessionStartTrackedRef.current = true;"), true);
  assert.equal(source.includes('if (isLearningSessionMode) {'), true);
  assert.equal(source.includes('return postJson("/api/session/answer", {'), true);
  assert.equal(source.includes("<SkillClearView"), true);
  assert.equal(source.includes("history={learningResult.history}"), true);
  assert.equal(source.includes('!isLearningSessionMode && selectedPath && ('), true);
});
