import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { readQuestSource } from "./helpers/quest-source.mjs";

const source = readQuestSource();

test("quest skill mode uses learning session lifecycle", () => {
  assert.equal(source.includes('const skillIdFromQuery = (params.get("skillId") ?? "").trim();'), true);
  assert.equal(source.includes('const retryFromQuery = (params.get("retry") ?? "").trim();'), true);
  assert.equal(source.includes('const isLearningSessionMode = Boolean(skillIdFromQuery);'), true);
  assert.equal(source.includes('fetch("/api/learning/session/start"'), true);
  assert.equal(source.includes('fetch(`/api/learning/session/${encodeURIComponent(sessionId)}`'), true);
  assert.equal(source.includes('fetch("/api/learning/session/answer"'), true);
  assert.equal(source.includes('fetch("/api/learning/session/finish"'), true);
  assert.equal(source.includes('import { trackAnalyticsEvent } from "@/lib/analytics";'), true);
  assert.equal(source.includes("const finishGuardRef = useRef(false);"), true);
  assert.equal(source.includes("const advanceGuardRef = useRef(false);"), true);
  assert.equal(source.includes("currentLearningIndex"), true);
  assert.equal(source.includes("const [learningAttemptCount,"), true);
  assert.equal(source.includes("quest.setLearningHint"), true);
  assert.equal(source.includes("quest.setLearningExplanation"), true);
  assert.equal(source.includes("currentLearningShowHint"), true);
  assert.equal(source.includes("currentLearningShowExplanation"), true);
  assert.equal(source.includes("currentLearningIsFallback"), true);
  assert.equal(source.includes("currentLearningFallbackCount"), true);
  assert.equal(source.includes("syncLearningUiFromSession"), true);
  assert.equal(source.includes("const learningProblem = isLearningSessionMode"), true);
  assert.equal(source.includes("currentSkillXP >= currentSkillRequiredXP"), true);
  assert.equal(source.includes("runFinishLearningSession"), true);
  assert.equal(source.includes('console.error("finish failed", error);'), true);
  assert.equal(source.includes("if(deps.finishGuardRef.current){"), true);
  assert.equal(source.includes("deps.finishGuardRef.current = true"), true);
  assert.equal(source.includes("deps.finishGuardRef.current = false"), true);
  assert.equal(source.includes("const useFastLearningLoop = isLearningSessionMode;"), true);
  assert.equal(source.includes("const FEEDBACK_FLASH_MS = 150;"), true);
  assert.equal(source.includes("const AUTO_ADVANCE_MS = 300;"), true);
  assert.equal(source.includes("queueAdvanceAfterFeedback"), true);
  assert.equal(source.includes("advanceGuardRef.current"), true);
  assert.equal(source.includes("advanceGuardRef.current = true"), true);
  assert.equal(source.includes("advanceGuardRef.current = false"), true);
  assert.equal(source.includes("setResultMark(\"wrong\");"), true);
  assert.equal(source.includes("}, FEEDBACK_FLASH_MS);"), true);
  assert.equal(source.includes("}, AUTO_ADVANCE_MS);"), true);
  assert.equal(source.includes("queueAdvanceAfterFeedback(verdict);"), true);
  assert.equal(source.includes("currentLearningShowHint"), true);
  assert.equal(source.includes("currentLearningShowExplanation"), true);
  assert.equal(source.includes('もう一度挑戦しよう'), true);
  assert.equal(source.includes('別の問題に挑戦しよう'), true);
  assert.equal(source.includes("!useFastLearningLoop && ("), true);
  assert.equal(
    source.includes('{resultMark === "correct" ? "Correct" : "Incorrect"}') ||
      source.includes('{args.resultMark === "correct" ? "Correct" : "Incorrect"}'),
    true
  );
  assert.equal(source.includes("index:answerIndex"), true);
  assert.equal(source.includes("answer:answerText"), true);
  assert.equal(source.includes("carryoverHistory: options?.carryoverHistory"), true);
  assert.equal(source.includes("recentProblems: options?.recentProblems"), true);
  assert.equal(source.includes("retryFromQuery"), true);
  assert.equal(source.includes("freshFromQuery || retryFromQuery"), true);
  assert.equal(source.includes("handleRetry"), true);
  assert.equal(source.includes("loadStateFromClient()"), true);
  assert.equal(source.includes("LEARNING_STATE_KEY"), true);
  assert.equal(source.includes('const LS_LEARNING_SESSION = "mq:learningSession";'), true);
  assert.equal(source.includes("const ORDER_LEGACY_PROMPT_RE = /小さいほうから|小さい順|ならべよう/u;"), true);
  assert.equal(source.includes("const ORDER_NUMERIC_ANSWER_RE = /^-?\\d+$/u;"), true);
  assert.equal(source.includes("const shouldForceFreshOrderSession = ("), true);
  assert.equal(source.includes('skillId === "E1_NUMBER_ORDER"'), true);
  assert.equal(source.includes("ORDER_LEGACY_PROMPT_RE.test(problem.problem.question)"), true);
  assert.equal(source.includes("!ORDER_NUMERIC_ANSWER_RE.test(problem.problem.answer)"), true);
  assert.equal(source.includes("if (storedSession.skillId !== skillId) {"), true);
  assert.equal(source.includes("if (shouldForceFreshOrderSession(skillId, storedSession)) {"), true);
  assert.equal(source.includes('console.info("[quest] stale order session detected; starting fresh session"'), true);
  assert.equal(source.includes('console.info("[quest] stale order session detected; starting fresh session"'), true);
  assert.equal(source.includes("clearLearningRecoveryStorage"), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_start");'), true);
  assert.equal(source.includes('trackAnalyticsEvent("session_finish");'), true);
  assert.equal(source.includes("sessionStartTrackedRef.current = true;"), true);
  assert.equal(source.includes('if (isLearningSessionMode) {'), true);
  assert.equal(source.includes('return postJson("/api/session/answer", {'), true);
  assert.equal(source.includes("<SkillClearView"), true);
  assert.equal(source.includes("history={resolvedLearningResult?.history ?? []}"), true);
  assert.equal(source.includes("learningRouting.handleRetry"), true);
  assert.equal(source.includes('!isLearningSessionMode && selectedPath && ('), true);
});
