import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const questPath = path.join(process.cwd(), "src/app/quest/page.tsx");
const source = fs.readFileSync(questPath, "utf8");

test("quest uses random pool questions and next-level navigation", () => {
  assert.equal(source.includes("const DEFAULT_TOTAL_QUESTIONS = 5;"), true);
  assert.equal(source.includes("const E1_SUMMARY_TYPE_ID = \"E1.NA.MIX.MIXED_TO_20\";"), true);
  assert.equal(source.includes("const E2_DAN_MUL_TYPE_RE = /^E2\\.NA\\.MUL\\.MUL_1D_1D_DAN_[1-9]$/;"), true);
  assert.equal(source.includes("const E2_MIX_TEN_TYPE_RE = /^E2\\.NA\\.MUL\\.MUL_1D_1D_MIX_(1_3|4_6|7_9)$/;"), true);
  assert.equal(source.includes("const E2_MIX_99_TEST_TYPE_ID = \"E2.NA.MUL.MUL_1D_1D_MIX_1_9\";"), true);
  assert.equal(source.includes("const getTargetQuestionCount = (typeId?: string, levelId?: string) =>"), true);
  assert.equal(source.includes("if (levelId === \"E1-12\") return 10;"), true);
  assert.equal(source.includes("if (levelId && isE1LevelId(levelId)) return DEFAULT_TOTAL_QUESTIONS;"), true);
  assert.equal(source.includes("if (typeId === E2_MIX_99_TEST_TYPE_ID) return 20;"), true);
  assert.equal(source.includes("if (E2_DAN_MUL_TYPE_RE.test(typeId)) return 9;"), true);
  assert.equal(source.includes("if (E2_MIX_TEN_TYPE_RE.test(typeId)) return 10;"), true);
  assert.equal(source.includes("if (typeId === E1_SUMMARY_TYPE_ID) return 10;"), true);
  assert.equal(source.includes("const QUESTION_POOL_SIZE = 50;"), true);
  assert.equal(source.includes("buildStocksForTypes("), true);
  assert.equal(source.includes("pickUniqueQuizFromStock("), true);
  assert.equal(source.includes("const sameTypeAcrossGrades = allCategoryItems.filter("), false);
  assert.equal(source.includes('setStatus("cleared");'), true);
  assert.equal(source.includes("<SkillClearView"), true);
  assert.equal(source.includes("if (v + 1 >= totalQuizQuestions)"), true);
  assert.equal(source.includes("const totalQuizQuestions = isLearningSessionMode"), true);
  assert.equal(source.includes(": Math.max(1, Math.min(targetQuestionCount, quizItems.length || targetQuestionCount));"), true);
  assert.equal(source.includes("setQuestionResults((prev) => ({"), true);
  assert.equal(source.includes("correctAnswer?: string"), true);
  assert.equal(source.includes("everWrong: boolean"), true);
  assert.equal(source.includes("firstWrongAnswer?: string"), true);
  assert.equal(source.includes("correct: !everWrong"), true);
  assert.equal(source.includes("if (isDrawingRef.current) return \"\";"), true);
  assert.equal(source.includes("splitComponentGreedyByProjection"), true);
  assert.equal(source.includes("splitByProjection(bin, w, h, pivot.bbox, true"), true);
  assert.equal(source.includes("history={learningResult.history}"), true);
  assert.equal(source.includes("onRetry={handleRetry}"), true);
  assert.equal(source.includes("onFinish={() => router.push(\"/skills\")}"), true);
  assert.equal(source.includes("router.push(\"/\");"), true);
  assert.equal(source.includes("status === 'playing' && (inputMode === 'numpad' ? ("), false);
  assert.equal(source.includes("data-testid=\"calc-memo-area\""), true);
  assert.equal(source.includes("計算メモ（2本指ピンチで縮小）"), true);
  assert.equal(source.includes("h-[40vh] min-h-[260px]"), true);
  assert.equal(source.includes("bg-white/90"), true);
  assert.equal(source.includes("w-full bg-white border border-slate-200 rounded-xl p-4 shadow-sm max-h-[48vh] overflow-y-auto"), false);
  assert.equal(source.includes("const FEEDBACK_FLASH_MS = 150;"), true);
  assert.equal(source.includes("const AUTO_ADVANCE_MS = 300;"), true);
  assert.equal(source.includes("const queueAdvanceAfterFeedback = (verdict: { ok: boolean }) => {"), true);
  assert.equal(source.includes("const clearPendingAdvanceTimers = useCallback(() => {"), true);
  assert.equal(source.includes("void runFinishLearningSession().catch((error: unknown) => {"), true);
  assert.equal(source.includes("void finishQuestLearningSession().catch((error: unknown) => {"), false);
  assert.equal(source.includes("bg-emerald-400/35"), true);
  assert.equal(source.includes("bg-red-500/35"), true);
  assert.equal(source.includes('{resultMark === "correct" ? "Correct" : "Incorrect"}'), true);
  assert.equal(source.includes("fixed inset-x-2 bottom-2"), false);
  assert.equal(source.includes("status === \"playing\" && ("), true);
  assert.equal(source.includes("selectedPath && ("), true);
  assert.equal(source.includes("まちがえた もんだい"), false);
  assert.equal(source.includes("`/quest?type=${encodeURIComponent(next.typeId)}&category=${encodeURIComponent(next.categoryId)}`"), true);
});
