import { useMemo } from "react";

export function useQuestUiWiring(args: any) {
  const {
    headerProps,
    quest,
    currentItem,
    currentType,
    combo,
    nextQuestion,
    uiText,
    isStarting,
    useSingleLineQa,
    useFastLearningLoop,
    currentCardRef,
    qaRowRef,
    qaPromptRef,
    qaPromptContentRef,
    qaAnswerRef,
    qaAnswerContentRef,
    currentAid,
    currentElementaryAid,
    currentSkillProgress,
    currentPatternPool,
    currentSessionSeed,
    currentLearningIndex,
    currentLearningIsFallback,
    currentLearningFallbackCount,
    isSecondaryQuest,
    isElementaryQuest,
    isHighSchoolQuest,
    isJuniorQuest,
    isLearningSessionMode,
    isQuadraticRootsQuestion,
    isH1ReferenceOnlyQuestion,
    isE1TwoLineQuestionLevel,
    isE2EqualShareType,
    showLearningHint,
    showLearningExplanation,
    showSecondaryHint,
    showSecondaryExplanation,
    showElementaryHint,
    showElementaryExplanation,
    showHighSchoolHint,
    setShowSecondaryHint,
    setShowSecondaryExplanation,
    setShowElementaryHint,
    setShowElementaryExplanation,
    setShowHighSchoolHint,
    renderPrompt,
    renderFractionEditorValue,
    renderAnswerWithSuperscript,
    qaPromptFontPx,
    qaAnswerFontPx,
    qaAnswerOffsetPx,
    fractionInput,
    inputMode,
    input,
    recognizedNumber,
    quadraticFractionInputs,
    quadraticAnswers,
    quadraticActiveIndex,
    setQuadraticActiveIndex,
    quizBuildError,
    router,
    setRetryNonce,
    describeStockReason,
    quizItems,
    emptyMessage,
    devMode,
    learningState,
    learningProblem,
    stockShortages,
    activePickMeta,
    activeStockInfo,
    quizSize,
    shouldAutoFinishLearningSession,
    skipFromExplanation,
    currentElementaryHintText,
    memoCanvas,
    memoCanvasHostRef,
    drawAreaRef,
    memoCanvasRef,
    shouldRenderElementaryExplanationPanel,
    isAnswerLockedByExplanation,
    canSubmitResolved,
    canUseKeyToken,
    setSettingsOpen,
    handleDelete,
    handleAttack,
    endLearningSession,
    sessionActionLoading,
    learningOrchestrator,
    setInput,
    setResultMark,
    setMessage,
    clearQuadraticFractionAutoMoveTimer,
    setQuadraticFractionInputs,
    setQuadraticAnswers,
    clearFractionAutoMoveTimer,
    setFractionInput,
    isFractionPartTokenValid,
    quadraticFractionAutoMoveTimerRefs,
    FRACTION_AUTO_MOVE_DELAY_MS,
    fractionAutoMoveTimerRef,
    VARIABLE_SYMBOLS
  } = args;

  const displayedAnswer = inputMode === "numpad" ? input : recognizedNumber ?? "";
  const resultOverlay = args.resultMark ? (
    <div className="pointer-events-none absolute inset-0 z-10 overflow-hidden rounded-[18px]">
      <div className={`absolute inset-0 ${args.resultMark === "correct" ? "bg-emerald-400/35" : "bg-red-500/35"}`} />
      <div className="absolute inset-0 bg-white/10" />
      <div className="absolute inset-0 flex items-center justify-center">
        <div
          className={`rounded-full px-4 py-2 text-sm font-black uppercase tracking-[0.3em] ${
            args.resultMark === "correct"
              ? "border border-emerald-100/80 bg-emerald-50/90 text-emerald-700"
              : "border border-red-100/80 bg-red-50/90 text-red-700"
          }`}
        >
          {args.resultMark === "correct" ? "Correct" : "Incorrect"}
        </div>
      </div>
    </div>
  ) : null;

  const memoProps = useMemo(() => ({
    undoMemo: memoCanvas.undoMemo,
    clearMemo: memoCanvas.clearMemo,
    memoCanvasHostRef,
    drawAreaRef,
    memoCanvasRef,
    handleMemoPointerDown: memoCanvas.handleMemoPointerDown,
    handleMemoPointerMove: memoCanvas.handleMemoPointerMove,
    handleMemoPointerEnd: memoCanvas.handleMemoPointerEnd,
    shouldRenderElementaryExplanationPanel
  }), [
    drawAreaRef,
    memoCanvas.clearMemo,
    memoCanvas.handleMemoPointerDown,
    memoCanvas.handleMemoPointerEnd,
    memoCanvas.handleMemoPointerMove,
    memoCanvas.undoMemo,
    memoCanvasHostRef,
    memoCanvasRef,
    shouldRenderElementaryExplanationPanel
  ]);

  const questionCardProps = useMemo(() => ({
      quest,
      currentItem,
      currentType,
      combo,
      nextQuestion,
      uiText,
      isStarting,
      useSingleLineQa,
      useFastLearningLoop,
      currentCardRef,
      qaRowRef,
      qaPromptRef,
      qaPromptContentRef,
      qaAnswerRef,
      qaAnswerContentRef,
      currentAid,
      currentElementaryAid,
      currentSkillProgress,
      currentPatternPool,
      currentSessionSeed,
      currentLearningIndex,
      currentLearningIsFallback,
      currentLearningFallbackCount,
      isSecondaryQuest,
      isElementaryQuest,
      isHighSchoolQuest,
      isLearningSessionMode,
      isQuadraticRootsQuestion,
      isH1ReferenceOnlyQuestion,
      isE1TwoLineQuestionLevel,
      isE2EqualShareType,
      showLearningHint,
      showLearningExplanation,
      showSecondaryHint,
      showSecondaryExplanation,
      showElementaryHint,
      showElementaryExplanation,
      showHighSchoolHint,
      setShowSecondaryHint,
      setShowSecondaryExplanation,
      setShowElementaryHint,
      setShowElementaryExplanation,
      setShowHighSchoolHint,
      renderPrompt,
      renderFractionEditorValue,
      renderAnswerWithSuperscript: (text?: string | null) =>
        renderAnswerWithSuperscript(text, isHighSchoolQuest),
      qaPromptFontPx,
      qaAnswerFontPx,
      qaAnswerOffsetPx,
      fractionInput,
      displayedAnswer,
      quadraticFractionInputs,
      quadraticAnswers,
      quadraticActiveIndex,
      setQuadraticActiveIndex,
      resultOverlay,
      quizBuildError,
      router,
      setRetryNonce,
      describeStockReason,
      quizItems,
      emptyMessage,
      devMode,
      learningState,
      learningProblem,
      stockShortages,
      activePickMeta,
      activeStockInfo,
      quizSize,
      shouldAutoFinishLearningSession,
      skipFromExplanation,
      currentElementaryHintText,
      ...memoProps
    }), [
      activePickMeta,
      activeStockInfo,
      combo,
      currentAid,
      currentCardRef,
      currentElementaryAid,
      currentElementaryHintText,
      currentItem,
      currentLearningFallbackCount,
      currentLearningIndex,
      currentLearningIsFallback,
      currentPatternPool,
      currentSessionSeed,
      currentSkillProgress,
      currentType,
      describeStockReason,
      devMode,
      displayedAnswer,
      emptyMessage,
      fractionInput,
      isE1TwoLineQuestionLevel,
      isE2EqualShareType,
      isElementaryQuest,
      isH1ReferenceOnlyQuestion,
      isHighSchoolQuest,
      isLearningSessionMode,
      isQuadraticRootsQuestion,
      isSecondaryQuest,
      isStarting,
      learningProblem,
      learningState,
      memoProps,
      nextQuestion,
      qaAnswerContentRef,
      qaAnswerFontPx,
      qaAnswerOffsetPx,
      qaAnswerRef,
      qaPromptContentRef,
      qaPromptFontPx,
      qaPromptRef,
      qaRowRef,
      quadraticActiveIndex,
      quadraticAnswers,
      quadraticFractionInputs,
      quizBuildError,
      quizItems,
      quizSize,
      renderAnswerWithSuperscript,
      renderFractionEditorValue,
      renderPrompt,
      resultOverlay,
      router,
      setQuadraticActiveIndex,
      setRetryNonce,
      setShowElementaryExplanation,
      setShowElementaryHint,
      setShowHighSchoolHint,
      setShowSecondaryExplanation,
      setShowSecondaryHint,
      shouldAutoFinishLearningSession,
      showElementaryExplanation,
      showElementaryHint,
      showHighSchoolHint,
      showLearningExplanation,
      showLearningHint,
      showSecondaryExplanation,
      showSecondaryHint,
      skipFromExplanation,
      stockShortages,
      uiText,
      useFastLearningLoop,
      useSingleLineQa,
      quest
    ]);

  return {
    displayedAnswer,
    resultOverlay,
    memoProps,
    headerProps,
    questionCardProps,
    keypadProps: {
      quest,
      isStarting,
      isAnswerLockedByExplanation,
      canSubmitResolved,
      canUseKeyToken,
      setSettingsOpen,
      handleDelete,
      handleAttack,
      endLearningSession,
      uiText,
      sessionActionLoading,
      isHighSchoolQuest,
      isJuniorQuest,
      learningOrchestrator,
      input,
      setInput,
      setResultMark,
      setMessage,
      isQuadraticRootsQuestion,
      quadraticAnswers,
      quadraticActiveIndex,
      clearQuadraticFractionAutoMoveTimer,
      setQuadraticFractionInputs,
      setQuadraticAnswers,
      clearFractionAutoMoveTimer,
      setFractionInput,
      fractionInput,
      quadraticFractionInputs,
      isFractionPartTokenValid,
      quadraticFractionAutoMoveTimerRefs,
      FRACTION_AUTO_MOVE_DELAY_MS,
      fractionAutoMoveTimerRef,
      isSecondaryQuest,
      VARIABLE_SYMBOLS
    }
  };
}
