export function useQuestHeaderProps(args: any) {
  const {
    quest,
    isLearningSessionMode,
    selectedPath,
    showGradeTypePicker,
    setShowGradeTypePicker,
    expandedGradePicker,
    setExpandedGradePicker,
    expandedGradeList,
    setExpandedGradeList,
    expandedProblemPicker,
    setExpandedProblemPicker,
    pendingGradeName,
    gradeOptions,
    pickerGradeId,
    setPendingGradeId,
    router,
    levelFromQuery,
    currentGradeOptionRef,
    currentProblemOptionRef,
    problemOptionsScrollRef,
    pickerGradeTypes,
    currentItem,
    currentType,
    learningProblem,
    getPracticeSkill,
    currentLearningSkillId,
    currentSkillXP,
    currentSkillRequiredXP,
    learningState,
    skillTree,
    setShowSkillTree,
    showSkillTree,
    currentSkillNode,
    recommendedSkillNode,
    SkillTreeView,
    nextQuestion,
    currentCardRef,
    combo,
    uiText
  } = args;

  const showCurrentSkillSummary =
    !isLearningSessionMode &&
    currentSkillNode != null &&
    quest.session == null &&
    quest.status !== "playing";

  return {
    headerProps: {
      quest,
      isLearningSessionMode,
      selectedPath,
      showGradeTypePicker,
      setShowGradeTypePicker,
      expandedGradePicker,
      setExpandedGradePicker,
      expandedGradeList,
      setExpandedGradeList,
      expandedProblemPicker,
      setExpandedProblemPicker,
      pendingGradeName,
      gradeOptions,
      pickerGradeId,
      setPendingGradeId,
      router,
      currentItem,
      currentType,
      levelFromQuery,
      currentGradeOptionRef,
      currentProblemOptionRef,
      problemOptionsScrollRef,
      pickerGradeTypes,
      currentCardRef,
      learningProblem,
      getPracticeSkill,
      currentLearningSkillId,
      currentSkillXP,
      currentSkillRequiredXP,
      learningState,
      skillTree,
      setShowSkillTree,
      showSkillTree,
      showCurrentSkillSummary,
      currentSkillNode,
      recommendedSkillNode,
      SkillTreeView,
      nextQuestion,
      uiText,
      combo
    }
  };
}
