import { KEYS } from "../keys";

export const ELEMENTARY_KEYPAD = [
  [KEYS.NUM_1, KEYS.NUM_2, KEYS.NUM_3],
  [KEYS.NUM_4, KEYS.NUM_5, KEYS.NUM_6],
  [KEYS.NUM_7, KEYS.NUM_8, KEYS.NUM_9],
  [KEYS.NUM_0, KEYS.FRACTION, KEYS.DECIMAL]
] as const;
