import { KEYS } from "../keys";

export const JUNIOR_KEYPAD = [
  [KEYS.NUM_1, KEYS.NUM_2, KEYS.NUM_3, KEYS.PAREN],
  [KEYS.NUM_4, KEYS.NUM_5, KEYS.NUM_6, KEYS.VAR],
  [KEYS.NUM_7, KEYS.NUM_8, KEYS.NUM_9, KEYS.PLUS_MINUS],
  [KEYS.NUM_0, KEYS.FRACTION, KEYS.EXPONENT, KEYS.DECIMAL]
] as const;
